<?php
return [

    'common_params' => [
        'export' => [
                'enabled' => true
        ],
        'responsive'  => [
            'enabled' => true
        ],
        'theme'                   => 'light',
        'chartCursor'             => [],
        'chartScrollbar'          => [
            'oppositeAxis'        => false,
            'offset'              => 30,
            'updateOnReleaseOnly' => true
        ],
        'legend' => [
            'enabled'                 => true,
            'useGraphSettings'        => false,
            'markerSize'              => 14,
            'markerType'              => 'circle',
            //'position'                => 'right',
            'useMarkerColorForLabels' => true,
            'useMarkerColorForValues' => true
        ],
        'allLabels'            => [],
        'balloon'              => [],
        'titles'               => [],
        'colors' => [
            ['#1ab394']
        ],
        'prefixesOfBigNumbers' => [
            [
                [
                    'number' => 1000,
                    'prefix' => 'K'
                ],
                [
                    'number' => 1000000,
                    'prefix' => 'M'
                ]
            ]
        ],
        'usePrefixes'        => true,
        'trendLines'         => [[]],
        'decimalSeparator'   => ',',
        'thousandsSeparator' => '.',
    ],

    'dayOfWeek' => [
        '1' => 'Monday',
        '2' => 'Tuesday',
        '3' => 'Wednesday',
        '4' => 'Thursday',
        '5' => 'Friday',
        '6' => 'Saturday',
        '7' => 'Sunday'
    ],

    'colors' => [
        'link'     => '#59c6c9',
        'photo'    => '#55ACEE',
        'video'    => '#3b5998',
        'status'   => '#1E2A3F',
        'event'    => '#7bb1c6',

        'likes'    => '#1E2A3F',
        'comments' => '#55ACEE',
        'shares'   => '#3b5998',
    ],

    'palettes' => [
        '#44c1bc',
        '#206035',
        '#909532',

    ],

    'maps' => [
        'AF' => 'afghanistanLow',
        'AL' => 'albaniaLow',
        'DZ' => 'algeriaLow',
        'AD' => 'andorraLow',
        'AO' => 'angolaLow',
        'AR' => 'argentinaLow',
        'AM' => 'armeniaLow',
        'AU' => 'australiaLow',
        'AT' => 'austriaLow',
        'AZ' => 'azerbaijanLow',
        'BS' => 'bahamasLow',
        'BH' => 'bahrainLow',
        'BD' => 'bangladeshLow',
        'BY' => 'belarusLow',
        'BE' => 'belgiumLow',
        'BZ' => 'belizeLow',
        'BT' => 'bhutanLow',
        'BO' => 'boliviaLow',
        'BA' => 'bosniaHerzegovinaCantonsLow',
        'BW' => 'botswanaLow',
        'BR' => 'brazilLow',
        'BN' => 'bruneiDarussalamLow',
        'BG' => 'bulgariaLow',
        'BF' => 'burkinaFasoLow',
        'BI' => 'burundiLow',
        'KH' => 'cambodiaLow',
        'CM' => 'cameroonLow',
        'CA' => 'canadaLow',
        'CV' => 'capeVerdeLow',
        'CF' => 'centralAfricanRepublicLow',
        'TD' => 'chadLow',
        'CL' => 'chileLow',
        'CN' => 'chinaLow',
        'CO' => 'colombiaLow',
        'CD' => 'congoDRLow',
        'CG' => 'congoLow',
        'CR' => 'costaRicaLow',
        'HR' => 'croatiaLow',
        'CU' => 'cubaLow',
        'CY' => 'cyprusLow',
        'UN' => 'cyprusNorthernCyprusLow',
        'GB' => 'unitedKingdomLow',
        'CZ' => 'czechRepublicLow',
        'DK' => 'denmarkLow',
        'DJ' => 'djiboutiLow',
        'DO' => 'dominicanRepublicLow',
        'EC' => 'ecuadorLow',
        'EG' => 'egyptLow',
        'SV' => 'elSalvadorLow',
        'EE' => 'estoniaLow',
        'FI' => 'finlandLow',
        'FR' => 'france2016Low',
        'GE' => 'georgiaLow',
        'DE' => 'germanyLow',
        'GR' => 'greeceLow',
        'GT' => 'guatemalaLow',
        'GN' => 'guineaLow',
        'GY' => 'guyanaLow',
        'HT' => 'haitiLow',
        'HN' => 'hondurasLow',
        'HK' => 'hongKongLow',
        'HU' => 'hungaryLow',
        'GL' => 'icelandLow',
        'IS' => 'icelandLow',
        'IN' => 'indiaLow',
        'ID' => 'indonesiaLow',
        'MY' => 'malaysiaLow',
        'IR' => 'iranLow',
        'IQ' => 'iraqLow',
        'IE' => 'irelandLow',
        'IL' => 'israelLow',
        'PS' => 'palestineLow',
        'VA' => 'italyLow',
        'SM' => 'sanMarinoLow',
        'MT' => 'italyLow',
        'IT' => 'italyLow',
        'JM' => 'jamaicaLow',
        'JP' => 'japanLow',
        'KZ' => 'kazakhstanLow',
        'KE' => 'kenyaLow',
        'XK' => 'kosovoLow',
        'KG' => 'kyrgyzstanLow',
        'LA' => 'laosLow',
        'LV' => 'latviaLow',
        'LT' => 'lithuaniaLow',
        'LU' => 'luxembourgLow',
        'LI' => 'liechtensteinHigh',
        'MK' => 'macedoniaLow',
        'ML' => 'maliLow',
        'MX' => 'mexicoLow',
        'MD' => 'moldovaLow',
        'MN' => 'mongoliaLow',
        'ME' => 'montenegroLow',
        'MA' => 'moroccoLow',
        'MM' => 'myanmarLow',
        'NP' => 'nepalLow',
        'NL' => 'netherlandsLow',
        'NZ' => 'newZealandLow',
        'NI' => 'nicaraguaLow',
        'NG' => 'nigeriaLow',
        'NO' => 'norwayLow',
        'AE' => 'unitedArabEmiratesLow',
        'OM' => 'omanLow',
        'PK' => 'pakistanLow',
        'PA' => 'panamaLow',
        'PY' => 'paraguayLow',
        'PE' => 'peruLow',
        'PH' => 'philippinesLow',
        'PL' => 'polandLow',
        'PT' => 'portugalLow',
        'PR' => 'puertoRicoLow',
        'US' => 'usaLow',
        'QA' => 'qatarLow',
        'RO' => 'romaniaLow',
        'RW' => 'rwandaLow',
        'SA' => 'saudiArabiaLow',
        'RS' => 'serbiaLow',
        'SG' => 'singaporeLow',
        'SK' => 'slovakiaLow',
        'SI' => 'sloveniaLow',
        'LS' => 'southAfricaLow',
        'ZA' => 'southAfricaLow',
        'KR' => 'southKoreaLow',
        'ES' => 'spainLow',
        'LK' => 'sriLankaLow',
        'SR' => 'surinameLow',
        'SE' => 'swedenLow',
        'CH' => 'switzerlandLow',
        'SY' => 'syriaLow',
        'TW' => 'taiwanLow',
        'TJ' => 'tajikistanLow',
        'TH' => 'thailandLow',
        'TR' => 'turkeyLow',
        'UG' => 'ugandaLow',
        'UA' => 'ukraineLow',
        'GG' => 'unitedKingdomLow',
        'JE' => 'unitedKingdomLow',
        'IM' => 'unitedKingdomLow',
        'UY' => 'uruguayLow',
        'UZ' => 'uzbekistanLow',
        'VE' => 'venezuelaLow',
        'VN' => 'vietnamLow',
        'YE' => 'yemenLow',
    ]
];